"""
FastAPI backend serving stock direction predictions from models trained by
models/train_final_model.py.

Deliberately thin: every route delegates to model_registry.py for loading
and to the metadata's own feature_columns list for feature selection, so
serving logic can never drift out of sync with how a model was actually
trained -- there is no second, hand-maintained list of feature names here
that could get out of date.

Run locally with:
    uvicorn backend.main:app --reload
Then visit http://127.0.0.1:8000/docs for interactive API documentation
(auto-generated by FastAPI from the type hints and schemas below -- nothing
extra to write for this).
"""
from typing import List

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware

from backend.model_registry import available_tickers, get_latest_feature_row, load_model_and_metadata
from backend.schemas import ModelInfo, PredictionResponse

app = FastAPI(
    title="Stock direction predictor API",
    description=(
        "Predicts next-day price DIRECTION (up/down), not price. "
        "Every prediction includes the model's honest walk-forward accuracy "
        "and majority-class baseline -- compare the two before trusting a prediction."
    ),
    version="0.1.0",
)

# Lets the Streamlit dashboard (a different process/port) call this API from
# the browser. Wide open (allow_origins=["*"]) is fine for local development;
# tighten this to your dashboard's actual origin before deploying publicly.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["GET", "POST"],
    allow_headers=["*"],
)


@app.get("/health")
def health():
    return {"status": "ok"}


@app.get("/models", response_model=List[ModelInfo])
def list_models():
    """Lists every ticker with a trained model available to /predict."""
    infos = []
    for ticker in available_tickers():
        _, metadata = load_model_and_metadata(ticker)
        infos.append(ModelInfo(
            ticker=metadata["ticker"],
            trained_at=metadata["trained_at"],
            training_rows=metadata["training_rows"],
            walk_forward_accuracy=metadata["walk_forward_mean_accuracy"],
            majority_baseline=metadata["walk_forward_mean_majority_baseline"],
        ))
    return infos


@app.post("/predict/{ticker}", response_model=PredictionResponse)
def predict(ticker: str):
    """Predicts next-day direction for `ticker` using its latest available
    feature row. 404s with a runnable command if the model or feature data
    doesn't exist yet -- the error message tells you exactly what to do,
    not just that something is missing."""
    try:
        model, metadata = load_model_and_metadata(ticker)
        feature_row, as_of_date = get_latest_feature_row(ticker, metadata["feature_columns"])
    except FileNotFoundError as e:
        raise HTTPException(status_code=404, detail=str(e))
    except ValueError as e:
        raise HTTPException(status_code=422, detail=str(e))

    X = feature_row.values.reshape(1, -1)
    prediction = int(model.predict(X)[0])

    confidence = None
    if hasattr(model, "predict_proba"):
        proba = model.predict_proba(X)[0]
        confidence = float(proba[prediction])

    return PredictionResponse(
        ticker=metadata["ticker"],
        as_of_date=str(as_of_date.date()) if hasattr(as_of_date, "date") else str(as_of_date),
        prediction=prediction,
        direction="up" if prediction == 1 else "down",
        confidence=confidence,
        walk_forward_accuracy=metadata["walk_forward_mean_accuracy"],
        majority_baseline=metadata["walk_forward_mean_majority_baseline"],
    )
